"""Put the package root on sys.path so tests can import the `scripts/` wrappers.

`scripts/` is intentionally not an installed package — the wrappers are CLI entry
points, not library code — so tests reach them as an implicit namespace package
rooted at the project directory.
"""

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))


def _usd_missing() -> list[str]:
    from isaaclab_microduck.assets.paths import ROBOT_MJCF, usd_path

    return [m for m in ROBOT_MJCF if not usd_path(m).is_file()]


#: Skip collection entirely when the USD assets have not been built.
#:
#: USD is a build artifact (gitignored, regenerated by `scripts/convert_assets.py`),
#: so a fresh clone has none. Scene cfgs call `make_microduck_cfg` at CLASS-BODY level,
#: which resolves the USD path eagerly and raises `FileNotFoundError` -- at import time,
#: before any test-level skip hook can run. That surfaced as a wall of collection errors
#: instead of a message saying what to do.
#:
#: The eager check is deliberate upstream (a silently stale robot is the worst failure
#: mode here), so this guards collection rather than weakening it.
#: Tests that do NOT build a task cfg, and so do not need the USD assets. Keeping this
#: list explicit means a USD-free test still runs on a fresh clone; a blanket ignore
#: silently skipped these too, which defeats having them.
_USD_FREE = {"test_policy_player_extension.py", "test_teleop_keys.py"}

_MISSING = _usd_missing()
collect_ignore_glob = [] if not _MISSING else None


def pytest_ignore_collect(collection_path, config):
    """Ignore only the cfg tests when USD is missing, not every test."""
    if not _MISSING:
        return False
    name = collection_path.name
    if not name.startswith("test_") or not name.endswith(".py"):
        return False
    return name not in _USD_FREE


def pytest_report_header(config):
    if _MISSING:
        return (
            f"USD assets not built ({len(_MISSING)} models missing) - cfg tests skipped "
            "(USD-free tests still run). Run: python scripts/convert_assets.py --force"
        )
    return None
